### ISSUE TITLE
What the shit

### ISSUE THREAD

**Issue by kenvix** [XCRailway/XCRailAdvancedReplacer#2]
ARE YOU F**KING TAKING A SHIT TO THE GITHUB?

**Comment by Frencis-fy** [comment]
interesting

**Comment by CSOLYOO** [comment]
This shit smell very..... Oh fuck

**Comment by fsgmhoward** [comment]
This guy is an idiot.... I just don't want to comment on his behavior any more.

Anyway, I have already reported this guy to Github team since he's just SPAMMING, making no contribution to Open Source, instead, just contaminating the presently good environment of Github.

So sickening... Just wait for the mods to judge this case.

**Comment by huihuimoe** [comment]
これはなんの状態なの。

**Comment by sohaking** [comment]
the funny thing is... he doesn't think he is an elementary school student.

**Comment by XCRailway** [comment]
![3 08urg cjd01ync 6b vb](https://cloud.githubusercontent.com/assets/20753800/17373371/7e9065ce-59da-11e6-8c19-3e4ccf9a77c8.jpg)

**Comment by paodan56** [comment]
@XCRailway 就你图多，就你图多。祝你明douc星hebag生活快乐，曹大佐~
![qq 20160805214004](https://cloud.githubusercontent.com/assets/20810502/17438402/345cd3e4-5b55-11e6-948a-74bbecb02150.png)
私认为国祥真乃人间の屑。
